### ISSUE TITLE
Is there a way to use a list of words instead

### ISSUE THREAD

**Issue by imranismail** [alco/hashids-elixir#12]
It would be pretty damn cool if there is a way to generate heroku-like hashed ID

```
coder = Hashids.new(words: ~w(elixir beautiful fox keg fire butterfly))

Hashids.encode(coder, 1)
#=> "elixir-fire-beautiful"
```

**Comment by alco** [comment]
I believe Heroku generates random word-phrases to be used as IDs. Converting numeric IDs to such word-phrases would result in strings that are too long, certainly not limited to 3 words.

Hashids only does number <-> string of characters conversions.

**Comment by AHBruns** [comment]
+1 this could make for some very nice use-cases.

**Comment by alco** [comment]
Closing as off-topic.
