### ISSUE TITLE
Possible Performance Optimization

### ISSUE THREAD

**Issue by hukl** [alco/hashids-elixir#13]
I did some profiling and a large amount (~30%) of time is spent for Lists.flatten

https://github.com/alco/hashids-elixir/blob/aa938d7780e07dee80cc8e9f08e6c5d8a590632d/lib/hashids/helpers.ex#L26

I just tried a variation but then realized that the variables contain lists themselves hence the need for flattening.

So I'm going to close the issue myself :)

**Comment by alco** [comment]
Hey @hukl. I'm all for optimizing the code but there hasn't been a need so far. Do you have a need to process a lot of hashids within a short time?
