### ISSUE TITLE
Binary pattern matching

### ISSUE THREAD

**Issue by pdilyard** [alco/hashids-elixir#7]
Are there a consistent number of bits that can be used in binary pattern matching on hashids?

ex:
```elixir
"groups:" <> <<gid :: 4>> <> ":users:" <> <<uid :: 4>>
```

**Comment by alco** [comment]
The length of the output strings is not limited, it depends on the magnitude of the input numbers.

You can pass the `min_len` option which will ensure that all output strings will be at least that long. If you know the range of the number you'll be encoding, you could find a value for `min_len` that would make all outputs have the same length. You'll just need to test it over the whole range of inputs to be sure.
