### ISSUE TITLE
How to Encode using a HEX string

### ISSUE THREAD

**Issue by dheenaINDIAN** [alco/hashids-elixir#8]
Hashids.encode(s, "590af91ca4175b2de68e73eb")

How to encode this binary id.

**Comment by alco** [comment]
This library encodes integer IDs to string ones. Did you mean `Hashids.decode`?

**Comment by dheenaINDIAN** [comment]
This library encodes integer IDs to string. 
Is there any way to encode "binary id (Mongo db id)" to string. 

Hashids.encode(Hashids.new([salt: "b831da2d9cc54b3a26bbad94751457107e55va693b61a9b654334fa7f30c9ec667", min_len: 12 ]), "590af91ca4175b2de68e73eb")

Because in Hashid support above feature in RubyOnRails, will tat same is supported in Elixer or not
