### ISSUE TITLE
Encode HEX string 

### ISSUE THREAD

**Issue by dheenaINDIAN** [alco/hashids-elixir#9]
This library encodes integer IDs to string.
Is there any way to encode "binary id (Mongo db id)" to string.

Hashids.encode(Hashids.new([salt: "b831da2d9cc54b78t5jhgg7t78766678668876786c667", min_len: 12 ]), "590af91ca4175b2de68e73eb")

Because HashId supports HEX encode , will tat same is supported in this library

**Comment by alco** [comment]
This won't be added as a feature to the library.

Here's a way to obfuscate a Hex string:

1. Call `String.to_integer(binary_id, 16)` to convert it to a number.
2. Encode the numeric id with Hashids.
3. After decoding an id with Hashids call `Integer.to_string(decoded_id, 16) |> String.downcase` to get a binary id back.
